5-1-Mogazoa/Mogazoa

.prettierrc
package-lock.json
package.json
src/lib/axiosInstance.ts
src/routes.ts

issue #1 
초기 프로젝트 구성 기능 추가
- 생략
- 초기 환경 구성 추가 (prettier 추가, baseurl 수정, useHook -ts 추가)
- 다들 화이팅

feat: 프로젝트 초기 구성 추가 구현

---

pages/_app.tsx
pages/index.tsx
styles/theme.ts

- issue #6 
- _app.tsx에 react query 추가,
- theme에 deviceSize 명칭 수정
- css 작업시 mobile 기준으로 작업 후 tablet, desktop 적용해서 미디어쿼리
-

feat: react query 추가, theme 수정

---

styles/GlobalStyle.ts

- issue #12 
- 전체 배경 재설정
- 생략
- *에 있던 background-color >> html 로 이동
-

design: 전체 배경 재설정

---

pages/product/[productId]/index.tsx
src/apis/product/index.ts
src/apis/product/schema.ts
src/components/product/ProductDetail.tsx
src/lib/axiosInstance.ts
src/routes.ts
styles/GlobalStyle.ts

- issue #17 
- apiCall과 getProductDetail 데이터요청함수(샘플) 추가
- axiosInstance.ts에 apiCall 함수 생성
- 데이터 요청하는 함수 샘플 만들어놓았습니다! 참고해서 만드시면 됩니다! src > apis > product > index.ts에 getProductDetail 함수(상품 상세 데이터)
예시코드1) 데이터 요청시 id값이 필요할때
export const getProductDetail = async (productId: number) => {
const requestProps = { method: "get", endPoint: API_ROUTE.PRODUCT_DETAIL(productId) };
return await apiCall(requestProps);
};
예시코드2) 데이터 요청시 id값이 필요없을때
export const getProductDetail = async () => {
const requestProps = { method: "get", endPoint: API_ROUTE.PRODUCT_DETAIL };
return await apiCall(requestProps);
};
- 페이지 안에서 불러올때 샘플은 pages > product > [productId] / index.tsx 참고하세요
-

Feat/17/apiCall과 getProductDetail 데이터요청함수(샘플) 추가

---

src/components/common/chip/Styled/StyledRankingChip.tsx

- issue #24 
- ranking chip 3위 이하 타입 통합
- 테스트 코드
-  실제 화면
- 3위 이하 타입 others로 통합
- 차후에 세부 구현에 맞게 수정하셔도 됩니다.
-

refactor: ranking chip 3위 이하 타입 통합

---

src/components/common/card/Card.tsx
src/components/common/card/Styled/StyledCard.tsx

- issue #19 
- card 컴포넌트 구현
1. 상위 컴포넌트 (e.g cardList 등)에서 prop로 내려주어야 합니다
imageUrl, imageAlt, cardProductTitle, review, pick, rateScore, productId
products를 조회해서 받아온 데이터 중
각 prop은 아래와 같습니다.
- imageUrl=image
- imageAlt= name
- cardProductTitle= name
- review = reviewCount
- pick= favoriteCount
- rateScore = rating
- productId = id
2. width값은 상위컴포넌트에서 한번더 div로 감싸준 뒤 적용해 주셔야 합니다!
(스크린샷은 상위컴포넌트에서 임의로 지정주었습니다!)
이후 레이아웃 잡을 때 grid나 flex로 조정하면 될 것 같아요!
3. 상품카드를 클릭하면 해당 상품의 디테일 페이지로 이동합니다.
-

Feat : card 컴포넌트 구현

---

pages/signup/index.tsx

- issue #48 
- 로그인 상태 시, signup페이지에서 홈페이지로 이동 
- accessToken이 있으면, signup페이지에서 / 로 이동합니다.
-

feat: signUp페이지 로그인 상태 시 홈페이지 이동

---

pages/signin/index.tsx

- issue #61 
- 로그인 상태에서 signin페이지 접근 시, /으로 이동
- accessToken정보를 브라우저가 가지고 있을 시, signin페이지에 접근하면 / 페이지로 이동합니다.
-

feat: 로그인 상태, signin페이지 접근하면 /으로 이동

---

pages/_app.tsx
src/components/gnb/GnbButton.tsx
src/components/gnb/Searchbar.tsx
src/components/gnb/Styled/StyledButton.tsx
src/components/gnb/Styled/StyledContainer.tsx
src/components/gnb/Styled/StyledMenuLogo.tsx
src/components/gnb/Styled/StyledSearchContainer.tsx
src/components/gnb/gnb.tsx

- issue #31 
- 간단한 설명
- 디자인은 구현이 됐지만 구체적인 메뉴 눌렀을 때 search 페이지로 이동하는 건 아직입니다! 
-

Design/31/Gnb 구현

---

README.md

- issue # 
- README.md 초안 작성 (우선 issue는 따로 안만들었습니다!)
-

Chore: README.md 초안

---

pages/oauth/signup/[provider].tsx
pages/signin/index.tsx
pages/signup/index.tsx
src/hooks/useCheckSignIn.ts
src/hooks/useCheckSignInAuthPage.ts

- issue #84 
- 로그인 체크 중복된 코드 커스텀 훅 변경 적용
- hook 기본 코드
- 적용법
- 로그인 체크 중복되는 코드를 커스텀 훅으로 변경하였습니다.
- 로그인 상태인 채로 접근 시 , / 페이지로 이동합니다.
-

feat: signIn 체크 Hook 생성 및 auth/oauth 페이지 적용

---

src/components/gnb/GnbButton.tsx
src/components/gnb/SideBar.tsx
src/components/gnb/Styled/StyledButton.tsx
src/components/gnb/gnb.tsx

- issue #77 
- 햄버거 버튼을 눌렀을 때 사이드바가 나오도록 구현했습니다
- 모바일 사이즈일때 검색창이 열리면 로고가 사라지는 부분 구현해서 다시 올릴예정입니다!

Feat: Sidebar 구현

---

src/apis/user/index.ts
src/types/user/userDataType.ts

- issue #100 
- user와 mypage에 필요한 api 구현
- 생략
- 
-

feat: mypage와 user 페이지에 필요한 api 구현

---

src/apis/auth/index.ts
src/components/auth/oauth/OauthSignUpForm.tsx
src/components/auth/signIn/SignInForm.tsx
src/components/auth/signUp/SignUpForm.tsx
src/hooks/useCheckSignInAuthPage.ts

- issue #98 
- Auth페이지 localStorage accessToken > Cookie로 변경
- 생략
- 기존 localStorage >> cookie 사용으로 변경했습니다.
- localStorage accessCookie는 다른페이지에서의 변경이 완료되면 삭제하도록 하겠습니다.
-

refactor: Auth페이지 localStorage accessToken > Cookie로 변경

---

pages/products/[productId]/index.tsx
src/apis/product/schema.ts
src/components/product/ReviewList/index.tsx
src/components/product/ReviewList/styled.tsx
src/utils/statisticalCalculator.tsx

- issue #81 
- 상품 상세 조회에 평균점수 데이터 추가되어서 연결함
- 리뷰 없을때 보일 스타일 추가
-

Design : 상품통계 평점 연결, 리뷰 없을때 스타일 추가

---

src/components/gnb/Searchbar.tsx
src/components/home/Category/category.tsx
src/hooks/useFilterSearch.ts

- issue #59 
- search 페이지 카테고리, 검색 기능 수정
- 기능은 같으며 코드 리팩토링 되었습니다.
-

refactor : search 페이지 카테고리, 검색 기능 수정

---

pages/test.tsx
src/apis/user/index.ts
src/components/common/input/Styled/StyledImageInput.tsx
src/components/product/ModalReview/index.tsx
src/components/profiles/FollowInfoModal.tsx
src/components/profiles/ProfileEditModal.tsx
src/components/profiles/Styled/StyledProfileEdit.tsx
src/types/user/userDataType.ts

- issue #105 
- 프로필 수정 모달 구현
-  이미지 미등록 시, 자동으로 기본이미지가 등록됩니다.
-  닉네임이 중복 시, 닉네임 중복 경고가 발생합니다.
- mypage 구현 완료되면 연결해야합니다.
- /test 페이지에서 임시로 프로필 편집가능하게 하였습니다.(로그인 상태)

feat: 프로필 수정 모달 구현

---

src/components/gnb/Searchbar.tsx
src/components/gnb/Styled/StyledContainer.tsx
src/components/gnb/gnb.tsx

- issue #116 
- gnb 오류 수정
-생략
-

fix:gnb 오류 수정

---

src/apis/follow/index.ts
src/components/profiles/FollowButton.tsx
src/components/profiles/Styled/StyledFollowButton.tsx

- issue #114 
- 간단한 설명
- 팔로우 버튼
- 팔로우 / 팔로우 취소 기능 구현
-

feat: 팔로우 버튼 / 기능 구현

---

pages/products/index.tsx
src/apis/product/index.ts
src/components/gnb/Searchbar.tsx
src/components/home/BaseCardList/BaseCardList.tsx
src/components/home/Category/CategoryList.tsx
src/components/search/SearchCardList/SearchCardList.tsx
src/components/search/SearchProducts/SearchProducts.tsx
src/components/search/SearchTitle/SearchTitle.tsx
src/components/search/getCategoryName.ts
src/hooks/useFilterSearch.ts
src/routes.ts

- issue #120 #106 
- 카테고리, 검색어입력, 정렬시 상품 조회 로직 수정
- 무한 스크롤 구현
- 카테고리, 검색어입력, 정렬시 해당 목록 조회 가능
- 무한 스크롤 구현
-

Fix : 상품조회 로직수정

---

package-lock.json
package.json
pages/products/[productId]/index.tsx
src/apis/product/index.ts
src/components/product/ReviewItem/index.tsx
src/components/product/ReviewList/index.tsx
src/components/product/ReviewList/styled.tsx

- issue #109 
- /products/[productId] 페이지에 상품 리뷰 목록 무한스크롤 리펙토링
- eact-intersection-observer 설치 (무한스크롤될 지점 감지시 사용)
https://github.com/5-1-Mogazoa/Mogazoa/assets/131663155/8eb4faa3-ed81-4fee-aae8-50ba753303a4
-

Feat : review 목록 무한스크롤 리펙토링

---

pages/products/[productId]/index.tsx
src/apis/review/index.ts
src/components/common/button/SortDropdown.tsx
src/components/common/modal/Modal.tsx
src/components/product/ModalDeleteReview/index.tsx
src/components/product/ModalReview/index.tsx
src/components/product/ReviewItem/ReviewFooter/index.tsx
src/components/product/ReviewItem/index.tsx
src/components/product/ReviewList/index.tsx
src/constant/MODAL_BUTTON.ts

- issue #129 
- 리뷰 삭제 모달(ModalDeleteReview) 구현 
https://github.com/5-1-Mogazoa/Mogazoa/assets/131663155/6118b244-c9fb-43c3-ac1d-1fcff40d8c5c
-

Feat: ModalDeleteReview 구현

---

src/apis/auth/index.ts
src/components/product/ProductDetail/ProductText/index.tsx
src/components/product/ProductDetail/index.tsx
src/components/product/ReviewItem/ReviewFooter/index.tsx
src/lib/axiosInstance.ts

- issue #132 
- interceptors랑 login 여부 확인할때 accessToken 확인하는 방식 수정
수정전: localstorage.getItem("accessToken");
수정후: getToken();
- getToken시 발생한 에러를 interceptor에서도 에러를 잡을 수 있게 throw error;추가

Fix: accessToken을 localStorage에서 cookie에서 가져오는 방식으로 수정

---

pages/mypage/index.tsx
pages/user/[userId]/index.tsx
src/hooks/useCheckSIgnin.ts

- issue #136 
- mypage 페이지 로그인 아닐 시, 메인 페이지로 이동
- mypage 페이지 로그인 아닐 시, 메인 페이지로 이동
-

feat: mypage 페이지 로그인 아닐 시, 메인 페이지로 이동

---

pages/_app.tsx
src/apis/oauth/index.ts
src/components/auth/oauth/OauthSignUpForm.tsx
src/components/oauth/OauthSignInBox.tsx

- issue #138 
- 카카오 간편 로그인 / 회원가입 구현
- 생략
- 카카오 간편 로그인 / 회원가입 구현
- 간편로그인 cookie 누락된 부분 추가
-

feat: 카카오 간편 로그인 / 회원가입 구현

---

package-lock.json
package.json
src/apis/image/index.tsx
src/components/profiles/ProfileEditModal.tsx

- issue #152 
- 이미지 등록시 random uid 생성 후 등록
-생략
- 이미지 등록시 uid를 생성하고, 해당 id를 파일이름으로 등록합니다.
- npm install short-unique-id 설치 후 진행하였습니다.
- pull 하신 후 'npm install' 하시면 됩니다!

feat: 이미지 등록시 random uid 생성 후 등록

---

src/apis/auth/index.ts
src/apis/category/index.ts
src/apis/category/schema.tsx
src/apis/follow/index.ts
src/apis/image/index.tsx
src/apis/product/index.ts
src/apis/product/schema.ts
src/apis/review/index.ts
src/apis/review/schema.ts
src/apis/user/index.ts
src/apis/user/schema.ts
src/components/product/ModalEdit/FormSelectProduct/index.tsx
src/lib/axiosInstance.ts

- issue #161 
- 멘토링때 피드백 반영해서 apis의 타입들 지정
-

Chore: apis 타입 지정

---

src/components/common/input/FormMultiImageInput/index.tsx
src/components/common/input/FormSelectCategory/index.tsx
src/components/product/ModalEdit/FormSelectProduct/index.tsx
src/components/product/ModalEdit/index.tsx
src/components/product/ProductDetail/index.tsx

- issue #165  
- issue #166 
- 상품편집(ModalEdit) 처음 열었을때 category가 제대로 실행안되는 문제 해결
=> useState와 useEffect를 사용해서 category가 처음에 undefined가 되었던 것을 바로 데이터 받자마자 구조분해해서 직접 내려줌
- products 타입에러 해결
-

Fix : 상품편집(ModalEdit)의 카테고리 버그 해결 #165 + 타입에러 해결 #166

---

pages/products/[productId]/index.tsx
src/components/product/ReviewList/index.tsx

- issue #180 
- products페이지의 리뷰 목록 조회를 서버사이드 랜더링에서 미리 받아오기
-

Chore: products페이지 리뷰목록 SSR적용

---

src/components/profiles/UserProfile.tsx

- issue #
- Fix: 프로필 이미지 shrink 적용
-

Fix: 프로필 이미지 shrink 적용

---

src/components/auth/oauth/OauthSignUpForm.tsx
src/components/auth/signIn/SignInForm.tsx
src/components/auth/signUp/SignUpForm.tsx
src/components/gnb/gnb.tsx
src/components/oauth/OauthSignInBox.tsx
src/components/profiles/MyPageProfileButtons.tsx

- issue #185 
- aceessToken 저장방식 변경 및 gnb 로그인 체크 방식 변경
- 로그아웃 gnb 최신화
- aceessToken 저장방식 변경 및 gnb 로그인 체크 방식 변경
- 로그아웃 시, gnb 버튼 최신화 안되는 현상 수정
-

auth,gnb - aceessToken 저장방식 변경 및 gnb 로그인 체크 방식 변경

---

src/components/profiles/FollowInfoModal.tsx
src/components/profiles/UserProfile.tsx

- issue #201 
- follow 모달 오류 수정
-  생략
- follow 모달 데이터 로드방법 수정
-

fix:follow 모달 오류 수정

---

src/components/common/button/Styled/StyledSelectDropdown.tsx

- issue #203 
- 상품편집 모달에서 상품명 입력시 폰트 컬러 수정
-

Design : Styled ModalEdit 입력 폰트 색변경

---

pages/products/[productId]/index.tsx
src/components/product/ReviewItem/index.tsx

- issue #211 
- localStorage is not defined 에러 해결(이전에 윤수님께서 말씀해주시긴 했는데 추가 수정합니다!)
Next.js에서 제공하는 Server Side Rendering(SSR)에서는 window, document 같은 브라우저 전역 객체를 사용할 수 없습니다. 
그리고 서버에서 생성한 초기화면(서버사이드 렌더링)과 그 후 작업되는 클라이언트에서 렌더링한 초기화면(클라이언트사이드 렌더링)이 서로 달라서 하이드레이션 오류가 발생하게 됩니다. 그래서 useEffect를 사용해서 페이지가 클라이언트에서 localStorage에 접근하도록 해야합니다.
에러 모습
-

Fix : localStorage is not defined 에러 해결

---

README.md

- issue #
- README.md 이미지를 gif로 변경
-

Chore: README.md 수정

---

src/components/common/button/Styled/StyledButton.tsx
src/components/compare/Styled/BodyContainer.tsx

- issue #220 
- 버튼 스타일 수정 (desktop에서 버튼 너비 100%로 수정)
-

Design: 버튼 수정
